<a href="https://colab.research.google.com/github/lilipant10/Sentiment-Analysis/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
df= pd.read_csv('https://raw.githubusercontent.com/Thinkful-Ed/data-science-lectures/master/customer_feedback_null.csv')
df

,dept_id,store_id,star_rating,state,num_employees,last_name_store_manager,temp
0,3531,M-551,4.0,Michigan,131,Patel,78
1,5473,T-323,5.0,Tennessee,59,Grainger,76
2,3987,F-772,3.0,Florida,42,Lee,98
3,8723,W-834,3.0,Washington,87,Ortinez,65
4,9932,A-993,NaN,Arizona,95,Robinson,89
5,1352,A-043,NaN,Alaska,102,Singh,42
6,4876,C-762,4.0,Colorado,68,Del Rey,55
7,7897,V-701,NaN,Vermont,51,Zhi,73
8,2764,K-434,3.0,Kentucky,73,Iwasake,81
9,7324,H-101,4.0,Hawaii,50,Stein-Brennen,79

In [3]:
df.sort_values(by=['star_rating'])

,dept_id,store_id,star_rating,state,num_employees,last_name_store_manager,temp
2,3987,F-772,3.0,Florida,42,Lee,98
3,8723,W-834,3.0,Washington,87,Ortinez,65
8,2764,K-434,3.0,Kentucky,73,Iwasake,81
0,3531,M-551,4.0,Michigan,131,Patel,78
6,4876,C-762,4.0,Colorado,68,Del Rey,55
9,7324,H-101,4.0,Hawaii,50,Stein-Brennen,79
1,5473,T-323,5.0,Tennessee,59,Grainger,76
4,9932,A-993,NaN,Arizona,95,Robinson,89
5,1352,A-043,NaN,Alaska,102,Singh,42
7,7897,V-701,NaN,Vermont,51,Zhi,73

In [4]:
df.sort_values(by=['star_rating'],ascending=False)

,dept_id,store_id,star_rating,state,num_employees,last_name_store_manager,temp
1,5473,T-323,5.0,Tennessee,59,Grainger,76
0,3531,M-551,4.0,Michigan,131,Patel,78
6,4876,C-762,4.0,Colorado,68,Del Rey,55
9,7324,H-101,4.0,Hawaii,50,Stein-Brennen,79
2,3987,F-772,3.0,Florida,42,Lee,98
3,8723,W-834,3.0,Washington,87,Ortinez,65
8,2764,K-434,3.0,Kentucky,73,Iwasake,81
4,9932,A-993,NaN,Arizona,95,Robinson,89
5,1352,A-043,NaN,Alaska,102,Singh,42
7,7897,V-701,NaN,Vermont,51,Zhi,73

In [6]:
df.sort_values(by=['star_rating','state'])

,dept_id,store_id,star_rating,state,num_employees,last_name_store_manager,temp
2,3987,F-772,3.0,Florida,42,Lee,98
8,2764,K-434,3.0,Kentucky,73,Iwasake,81
3,8723,W-834,3.0,Washington,87,Ortinez,65
6,4876,C-762,4.0,Colorado,68,Del Rey,55
9,7324,H-101,4.0,Hawaii,50,Stein-Brennen,79
0,3531,M-551,4.0,Michigan,131,Patel,78
1,5473,T-323,5.0,Tennessee,59,Grainger,76
5,1352,A-043,NaN,Alaska,102,Singh,42
4,9932,A-993,NaN,Arizona,95,Robinson,89
7,7897,V-701,NaN,Vermont,51,Zhi,73

In [9]:
import pandas as pd
df= pd.read_csv('https://raw.githubusercontent.com/Thinkful-Ed/data-science-lectures/master/emp_vacation_hours.csv')

In [10]:
df.sum()

emp_id                    569832
vacation_hrs_avail         12891
vacation_hrs_used           6004
vacation_hrs_remaining      6887
dtype: int64

In [11]:
df.count()

emp_id                    100
vacation_hrs_avail        100
vacation_hrs_used         100
vacation_hrs_remaining    100
dtype: int64

In [12]:
df.mean()

emp_id                    5698.32
vacation_hrs_avail         128.91
vacation_hrs_used           60.04
vacation_hrs_remaining      68.87
dtype: float64

In [13]:
df.median()

emp_id                    6253.5
vacation_hrs_avail         135.0
vacation_hrs_used           47.0
vacation_hrs_remaining      61.0
dtype: float64

In [14]:
df.mode()

    emp_id  vacation_hrs_avail  vacation_hrs_used  vacation_hrs_remaining
0     1014               200.0               40.0                     0.0
1     1129                 NaN                NaN                     NaN
2     1144                 NaN                NaN                     NaN
3     1290                 NaN                NaN                     NaN
4     1351                 NaN                NaN                     NaN
..     ...                 ...                ...                     ...
95    9547                 NaN                NaN                     NaN
96    9564                 NaN                NaN                     NaN
97    9645                 NaN                NaN                     NaN
98    9825                 NaN                NaN                     NaN
99    9996                 NaN                NaN                     NaN

[100 rows x 4 columns]

In [16]:
df.min()

emp_id                    1014
vacation_hrs_avail          40
vacation_hrs_used            9
vacation_hrs_remaining       0
dtype: int64

In [17]:
df.max()

emp_id                    9996
vacation_hrs_avail         200
vacation_hrs_used          200
vacation_hrs_remaining     191
dtype: int64

In [18]:
df.std()

emp_id                    2706.766974
vacation_hrs_avail          52.353325
vacation_hrs_used           43.839911
vacation_hrs_remaining      49.705325
dtype: float64